#!/bin/bash

# Script: run-unit-tests.sh
# Purpose: Run CodeQL unit tests for generated queries
# Usage: ./run-unit-tests.sh [OPTIONS]

set -euo pipefail

# Color codes for output
readonly RED='\033[0;31m'
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[1;33m'
readonly BLUE='\033[0;34m'
readonly NC='\033[0m' # No Color

# Logging functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1" >&2
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1" >&2
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1" >&2
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1" >&2
}

# Configuration - Centralized path variables
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
QLT_PROJECT_DIR="$REPO_ROOT/src/CodeQLToolkit.Core"
QLT_PROJECT_FILE="$QLT_PROJECT_DIR/CodeQLToolkit.Core.csproj"

# Default configuration
TEST_DIR=""
LANGUAGES=""
VERBOSE=false
HELP=false

# Usage information
show_help() {
    cat << EOF
Usage: $0 [OPTIONS]

Run CodeQL unit tests for generated queries in a test directory.

OPTIONS:
    -d, --test-dir DIR          Test directory containing language subdirectories
    -l, --languages LANGS       Comma-separated list of languages to test (e.g., "python,java")
    -v, --verbose               Enable verbose output
    -h, --help                  Show this help message

EXAMPLES:
    $0 --test-dir /tmp/qlt-test --languages python,java
    $0 -d /tmp/qlt-test -l python -v

DESCRIPTION:
    This script runs CodeQL unit tests for queries generated by the CodeQL Toolkit.
    It expects a directory structure like:

    TEST_DIR/
    ├── python/
    │   └── testpack-python/
    │       └── test/
    └── java/
        └── testpack-java/
            └── test/

    The script will:
    1. Execute unit tests for each language
    2. Validate test results
    3. Generate a summary report

EOF
}

# Parse command line arguments
parse_args() {
    while [[ $# -gt 0 ]]; do
        case $1 in
            -d|--test-dir)
                TEST_DIR="$2"
                shift 2
                ;;
            -l|--languages)
                LANGUAGES="$2"
                shift 2
                ;;
            -v|--verbose)
                VERBOSE=true
                shift
                ;;
            -h|--help)
                HELP=true
                shift
                ;;
            *)
                log_error "Unknown option: $1"
                show_help
                exit 1
                ;;
        esac
    done
}

# Validate required parameters
validate_params() {
    if [[ "$HELP" == "true" ]]; then
        show_help
        exit 0
    fi

    if [[ -z "$TEST_DIR" ]]; then
        log_error "Test directory is required. Use --test-dir option."
        show_help
        exit 1
    fi

    if [[ ! -d "$TEST_DIR" ]]; then
        log_error "Test directory does not exist: $TEST_DIR"
        exit 1
    fi

    if [[ -z "$LANGUAGES" ]]; then
        log_error "Languages are required. Use --languages option."
        show_help
        exit 1
    fi
}

# Execute unit tests for a language
run_unit_tests() {
    local language="$1"
    local work_dir="$2"

    log_info "Running unit tests for $language..."

    # Get environment info
    local os_name=$(uname -s)
    if [[ "$os_name" == "Darwin" ]]; then
        os_name="macOS"
    fi

    log_info "  → Environment: $os_name, CodeQL CLI: Startup...
unknown, Stdlib: codeql-cli_vStartup...
unknown"

    # Find the QLT project using centralized variables
    if [[ ! -f "$QLT_PROJECT_FILE" ]]; then
        log_error "Could not find QLT project at: $QLT_PROJECT_FILE"
        return 1
    fi

    # Change to the work directory since that's where QLT expects to be run from
    local old_pwd=$(pwd)
    cd "$work_dir" || return 1

    # Create test results directory for the language
    local test_results_dir="${work_dir}/${language}/test-results"
    mkdir -p "$test_results_dir"

    # Execute tests using dotnet run
    local test_output
    if ! test_output=$(dotnet run --project "$QLT_PROJECT_FILE" -- test run execute-unit-tests \
        --language "$language" \
        --num-threads 2 \
        --work-dir "$test_results_dir" \
        --runner-os "$os_name" \
        --automation-type actions 2>&1); then
        log_error "Unit test execution failed for $language"
        if [[ "$VERBOSE" == "true" ]]; then
            log_error "$test_output"
        fi
        cd "$old_pwd"
        return 1
    fi

    cd "$old_pwd"

    if [[ "$VERBOSE" == "true" ]]; then
        log_info "Test execution output for $language:"
        echo "$test_output"
    fi

    log_success "Unit tests completed for $language"
    return 0
}

# Validate unit test results
validate_test_results() {
    local language="$1"
    local work_dir="$2"

    log_info "Validating unit test results for $language..."

    local results_dir="${work_dir}/${language}/test-results"
    if [[ ! -d "$results_dir" ]]; then
        log_error "Test results directory not found: $results_dir"
        return 1
    fi

    # Find the QLT project using centralized variables
    if [[ ! -f "$QLT_PROJECT_FILE" ]]; then
        log_error "Could not find QLT project at: $QLT_PROJECT_FILE"
        return 1
    fi

    # Change to the work directory since that's where QLT expects to be run from
    local old_pwd=$(pwd)
    cd "$work_dir" || return 1

    local validation_output
    if ! validation_output=$(dotnet run --project "$QLT_PROJECT_FILE" -- test run validate-unit-tests --pretty-print --results-directory "$results_dir" 2>&1); then
        log_error "Test result validation failed"
        if [[ "$VERBOSE" == "true" ]]; then
            log_error "$validation_output"
        fi
        cd "$old_pwd"
        return 1
    fi

    cd "$old_pwd"

    if [[ "$VERBOSE" == "true" ]]; then
        log_info "Validation output:"
        echo "$validation_output"
    fi

    log_success "Test result validation passed"
    return 0
}

# Main execution function
main() {
    parse_args "$@"
    validate_params

    log_info "Starting unit test execution..."
    log_info "Test directory: $TEST_DIR"
    log_info "Languages: $LANGUAGES"

    # Convert comma-separated languages to array
    IFS=',' read -ra LANG_ARRAY <<< "$LANGUAGES"

    local passed=0
    local failed=0
    local failed_languages=()

    # Process each language
    for language in "${LANG_ARRAY[@]}"; do
        language=$(echo "$language" | xargs) # trim whitespace

        log_info "Processing language: $language"

        # Check if language directory exists
        local lang_dir="$TEST_DIR/$language"
        if [[ ! -d "$lang_dir" ]]; then
            log_warning "Language directory not found: $lang_dir, skipping..."
            continue
        fi

        # Run tests for this language
        local language_failed=false
        if ! run_unit_tests "$language" "$TEST_DIR"; then
            log_error "Unit test execution failed for $language"
            language_failed=true
        fi

        # Update counters
        if [[ "$language_failed" == "true" ]]; then
            ((failed++))
            failed_languages+=("$language")
            log_error "Language $language validation failed"
        else
            ((passed++))
            log_success "Language $language validation complete"
        fi

        # Validate all test results if any tests were run
        if [[ $((passed + failed)) -gt 0 ]]; then
            if ! validate_test_results "$language" "$TEST_DIR"; then
                log_error "Unit test validation failed"
                ((failed++))
            else
                log_success "Unit test validation passed"
            fi
        fi
    done

    # Print summary
    echo
    log_info "=== Unit Test Summary ==="
    log_success "Unit Tests Passed: $passed"
    if [[ $failed -gt 0 ]]; then
        log_error "Unit Tests Failed: $failed"
        if [[ ${#failed_languages[@]} -gt 0 ]]; then
            log_error "Unit Tests Failed for Languages: ${failed_languages[*]}"
        fi
    else
        log_success "No Unit Tests Failed"
    fi

    if [[ $failed -eq 0 ]]; then
        log_success "All unit tests passed! 🎉"
        exit 0
    else
        log_error "Some unit tests failed. 😞"
        exit 1
    fi
}

# Run main function with all arguments
main "$@"
