name: Build Linux

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.142
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --c Release --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    
    # create archive in \src\CodeQLToolkit.Core\bin\Release\net6.0\publish\linux-x64
    - name: Create Build Bundle (Linux)
      shell: pwsh
      run: |
        dotnet publish /p:PublishProfile=.\src\CodeQLToolkit.Core\Properties\PublishProfiles\Linux-Profile.pubxml
        $version = Get-Content version 
        $version = $version.Trim()
        Compress-Archive -Path .\src\CodeQLToolkit.Core\bin\Release\net6.0\publish\linux-x64\* -DestinationPath qlt-$version.zip

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ZIP Bundle
        path: qlt*.zip
