name: 🍏 Build Release (MacOS arm64)

on:
  workflow_call:
    inputs:
        version:
          description: |
            The version to release. (eg: 0.1.2, exclude the 'v'.). 
          required: true
          type: string 

jobs:
  build-macos64:
    runs-on: macos-14 # note this is arm64
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore

    - name: Build Bundle
      shell: bash
      run: |
        echo "Current Directory $(pwd)"
        # build the project 
        dotnet publish ./src/CodeQLToolkit.Core/CodeQLToolkit.Core.csproj /p:PublishProfile=./src/CodeQLToolkit.Core/Properties/PublishProfiles/MacOS-arm64-Profile.pubxml
        cp ./src/CodeQLToolkit.Core/bin/Release/net6.0/publish/macos-arm64/CodeQLToolkit.Core ./src/CodeQLToolkit.Core/bin/Release/net6.0/publish/macos-arm64/qlt
        
        # repair permissions
        chmod +x ./src/CodeQLToolkit.Core/bin/Release/net6.0/publish/macos-arm64/qlt
        chmod -R +r ./src/CodeQLToolkit.Core/bin/Release/net6.0/publish/macos-arm64                    

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Build CodeQL Bundle Tool for Packaging
      shell: pwsh 
      run: |
        # need this for the bundling to work.
        pip install poetry 
        pip install -U pyinstaller 

        # run the packaging 
        ./scripts/build_codeql_bundle_dist.ps1 -Version 0.2.1 -WorkDirectory dist -DestinationDirectory ./src/CodeQLToolkit.Core/bin/Release/net6.0/publish/macos-arm64/tools/
      env:
        GH_TOKEN: ${{ github.token }}


    - name: Build Bundle Archive
      shell: bash
      run: |
        echo "Current Directory $(pwd)"

        # create bundle 
        ARCHIVE="$(pwd)/qlt-macos-arm64.zip"        
        pushd ./src/CodeQLToolkit.Core/bin/Release/net6.0/publish/macos-arm64
        zip -r $ARCHIVE .
        popd

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: qlt-dist
        path: qlt*.zip

    - name: Upload Build Artifacts
      shell: pwsh
      run: |
        Write-Host (Get-Location)
        gh release upload v${{inputs.version}} ./qlt-macos-arm64.zip
      env:
        GH_TOKEN: ${{ github.token }}
