name: ⚙️ Validate Workflow Files

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  validate-workflow-files:
    name: Validate Workflow Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install QLT
        id: install-qlt
        uses: ./.github/actions/install-qlt-local
        with:
          qlt-version: 'latest'
          add-to-path: true

      - name: Validate QLT Installation
        shell: bash
        run: |
          echo -e "Checking QLT Version:"
          echo "QLT Home: ${{ steps.install-qlt.outputs.qlt-home }}"
          qlt version

      - name: Generate Workflow Files (Test Feature)
        shell: bash
        run: |
          qlt test init  --use-runner ubuntu-latest --num-threads 4 --language cpp --automation-type actions --development --overwrite-existing


      - name: Check Git Clean Status 
        shell: bash
        run: |
          if git diff-index --quiet HEAD .github ; then
            echo "Git is clean - generation is as expected."
          else
            echo "Some files have changed - please check for regressions."
            git status
            git diff-index HEAD .github
            exit 1
          fi


