name: Build Release (Linux x64)

on:
  workflow_call:
    inputs:
        version:
          description: |
            The version to release. (eg: 0.1.2, exclude the 'v'.). 
          required: true
          type: string 
  
  
jobs:
  build-linux64:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore

    - name: Build Bundle (Linux)
      shell: bash
      run: |
        echo "Current Directory $(pwd)"
        # build the project 
        dotnet publish ./src/CodeQLToolkit.Core/CodeQLToolkit.Core.csproj /p:PublishProfile=./src/CodeQLToolkit.Core/Properties/PublishProfiles/Linux-Profile.pubxml
        cp ./src/CodeQLToolkit.Core/bin/Release/net6.0/publish/linux-x64/CodeQLToolkit.Core ./src/CodeQLToolkit.Core/bin/Release/net6.0/publish/linux-x64/qlt
        
        # repair permissions
        chmod +x ./src/CodeQLToolkit.Core/bin/Release/net6.0/publish/linux-x64/qlt
        chmod +r -R ./src/CodeQLToolkit.Core/bin/Release/net6.0/publish/linux-x64        
        
        # create bundle 
        ARCHIVE="$(pwd)/qlt-linux-x86_64.zip"        
        pushd ./src/CodeQLToolkit.Core/bin/Release/net6.0/publish/linux-x64
        zip -r $ARCHIVE .
        popd

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: qlt-dist
        path: qlt*.zip

    - name: Upload Build Artifacts
      shell: pwsh
      run: |
        Write-Host (Get-Location)
        gh release upload v${{inputs.version}} ./qlt-linux-x86_64.zip
      env:
        GH_TOKEN: ${{ github.token }}
